name: 'cargo-bloat'
description: 'Track rust bloat across builds'
author: 'orf'
branding:
  icon: box
  color: blue
inputs:
  token:
    description: 'Github token to use'
    required: true
  bloat_args:
    description: 'Custom args to pass to bloat'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
