name: 'cargo-bloat'
description: 'Track rust bloat across builds'
author: 'orf'
branding:
  icon: box
  color: blue
#inputs:
#  myInput:
#    description: 'input description here'
#    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
